<LoginScreen>:
    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'center'

        BoxLayout:
            size_hint: (0.3, 0.3)
            
            orientation: 'vertical'

            TextInput:
            TextInput:
                password: True

            GridLayout:
                cols: 2

                Button:
                    text: 'Login'
                
                Button:
                    text: 'Signup'

